# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile-pictures', verbose_name='عکس پروفایل'),
        ),
    ]
