# Generated by Django 2.1.3 on 2018-11-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20181118_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedFreeTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.TeacherFreeTimes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Student')),
            ],
        ),
        migrations.AddField(
            model_name='teacherfreetimes',
            name='reserved',
            field=models.ManyToManyField(blank=True, default=[], through='people.ReservedFreeTimes', to='people.Student'),
        ),
    ]
