# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20181117_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherfreetimes',
            options={'verbose_name_plural': 'Teacher Free Times'},
        ),
    ]
