# Generated by Django 2.1.3 on 2018-11-18 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20181118_0851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservedfreetimes',
            options={'verbose_name_plural': 'Reserved Free Times'},
        ),
    ]
