# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20181109_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to=people.models.get_picture_filename, verbose_name='عکس پروفایل'),
        ),
    ]
