# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 13:46
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20181109_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=markdownx.models.MarkdownxField(blank=True, max_length=500, verbose_name='زندگی نامه'),
        ),
    ]
