# Generated by Django 2.1.3 on 2018-11-19 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20181119_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code_expire_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 19, 14, 31, 32, 994381, tzinfo=utc)),
        ),
    ]
