# Generated by Django 2.1.3 on 2018-11-19 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20181119_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code_expire_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
