# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_teacherfreetimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherfreetimes',
            name='student_capacity',
            field=models.PositiveIntegerField(verbose_name='ظرفیت'),
        ),
    ]
